name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      # - uses: actions/cache@v1
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      - run: npm i

      - name: Lint
        run: npm run lint

      - name: Build UI Library
        run: npm run ng -- build ui

      - name: Build Example Pages
        run: npm run ng -- build ui-example

      - name: Karma Test UI Library
        run: npm run test -- ui
              --no-watch
              --no-progress
              --browsers=ChromeHeadlessCI

      - name: Karma Test UI Example Pages
        run: npm run test -- ui-example
              --no-watch
              --no-progress
              --browsers=ChromeHeadlessCI

      - name: Protractor Test UI Example Pages
        run: npm run ng -- e2e
              --protractor-config=projects/ui-example/e2e/protractor-ci.conf.js

      - name: Build storybook
        run: npm run build-storybook

      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Build and Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          SSH: true
          BRANCH: gh-pages
          FOLDER: .storybook-out
