# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: ./.github/actions/node-setup
      - uses: ./.github/actions/npm-cache

      - run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build UI Library
        run: npm run ng -- build ui

      - name: Build Example Pages
        run: npm run ng -- build ui-example

      - name: Karma Test UI Library
        run: npm run test -- ui --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Karma Test UI Example Pages
        run: npm run test -- ui-example --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Protractor Test UI Example Pages
        run: npm run ng -- e2e --protractor-config=projects/ui-example/e2e/protractor-ci.conf.js

      - name: Build storybook
        run: npm run build-storybook

      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Build and Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          SSH: true
          BRANCH: gh-pages
          FOLDER: .storybook-out
